[WIP] Feat/gui windows [
Kubaaa96/Idle-Roman-Empire pull request #15
Opened 2020-10-23 14:06 UTC by Kubaaa96

#3

2020-10-23 15:12 UTC, Sopel97 requested changes

2020-10-23 15:12 UTC, Sopel97 commented on src/core/Engine.cpp
> +        containerPtr->getWidgets()[0]->setPosition({ 100, 100 });
Does this even compile? `getWidgets` returns `const vector<unique_ptr<...>>&` so I don't think it allows modification of the inner widgets. Anyway, this leaks implementation details, there is no guarentee about the order in which widgets are stored. The properties of the button should be set before putting it into the container.add(std::unique_ptr<T> widget)` that dispatches to a virtual add method

2020-10-23 15:12 UTC, Sopel97 commented on src/core/Engine.cpp
> +        , containerPtr(std::make_unique<ire::core::widgets::Container>())
`m_containerPtr`. I'm also not sure about adding the `Ptr` suffix to instances of unique_ptr. I don't think it conveys additional information when there are no variables of type `Container` in the scope

2020-10-23 15:12 UTC, Sopel97 commented on src/core/widgets/Button.cpp
> +		m_type = "Button";
I don't like the idea of using strings as widget types. Considering that user provided widgets should be possible this cannot be a simple enum though. I would consider an implementation like this
```
struct WidgetType { 
    uint64_t index; 
    std::string_view name;
    operator==(...) { return lhs.index == rhs.index }
    operator<(...) { return lhs.index < rhs.index }
    ...
    template <typename T>
    static WidgetType create(std::string_view name) { 
        static std::atomic<uint64_t> nextId{0};
        return { nextId.fetch_add(1), name }; 
    }
};
...
struct Widget {
    ...
    virtual WidgetType getType() const = 0;
};
...
struct Button {
    ...
    static WidgetType type = WidgetType::create<Button>("Button");
    WidgetType getType() const override { return Type; }
};
```

2020-10-23 15:12 UTC, Sopel97 commented on src/core/widgets/Button.h
> +        std::unique_ptr<Button> create(const std::string& text = "");
hmm, why is this not a static method?

2020-10-23 15:12 UTC, Sopel97 commented on src/core/widgets/Button.h
> +        void draw(sf::RenderWindow& window) const override;
`draw` should take `sf::RenderTarget&` instead of `sf::RenderWindow&`. It would be more generic.

2020-10-23 15:12 UTC, Sopel97 commented on src/core/widgets/ClickableWidget.cpp
> +	ClickableWidget::ClickableWidget()
I don't quite get the point of this concept of `ClickableWidget`. Almost all widgets have some action on mouse click, so this feels like it will only complicate event dispatch (because how will you call `onClick` generically?).

2020-10-23 15:12 UTC, Sopel97 commented on src/core/widgets/Container.cpp
> +		m_containerWidget = true;
why is this state needed?

2020-10-23 15:12 UTC, Sopel97 commented on src/core/widgets/Container.cpp
> +					// TODO add some debug logger information later
The caller should be informed that the widget with this name already exists. Currently the request to add the widget is silently ignored.

2020-10-23 15:12 UTC, Sopel97 commented on src/core/widgets/Container.cpp
> +		widgetPtr->setWidgetName(widgetName);
wouldn't it be better if the widget name had to be set before calling `add` and this function would use that widget's name?

2020-10-23 15:12 UTC, Sopel97 commented on src/core/widgets/Container.cpp
> +		if (!m_widgets.empty())
`std::erase(std::find_if(begin(m_widgets), end(m_widgets), []() {...}))`

2020-10-23 15:12 UTC, Sopel97 commented on src/core/widgets/Container.cpp
> +	Widget* Container::get(int index)
missing overloads for `const` `this`

2020-10-23 15:12 UTC, Sopel97 commented on src/core/widgets/Container.cpp
> +		return m_widgets[index].get()->getWidgetName().compare(name) == 0;
`std::string::operator==` ?

2020-10-23 15:12 UTC, Sopel97 commented on src/core/widgets/Container.cpp
> +		return m_widgets[index].get()->getWidgetName().compare(name) == 0;
What if widget's name changes to a duplicated one once it's already inserted to the container? Maybe widgets shouldn't have a name and instead only have names for widgets inserted in a container?. Maybe completely remove the names and return a pointer to the inserted widget from `add` and let the caller worry about getting the one he wants.  I was thinking about something like http://coliru.stacked-crooked.com/a/bc673fea27223a51 (this also addresses the second comment in this review)

2020-10-23 15:12 UTC, Sopel97 commented on src/core/widgets/Container.h
> +        // Widget Name Should not contain whitespaces
hmm, why is that?

2020-10-23 15:12 UTC, Sopel97 commented on src/core/widgets/Container.h
> +        std::unique_ptr<Widget> clone() const override
shouldn't clone work the same as for other widgets?

2020-10-23 15:12 UTC, Sopel97 commented on src/core/widgets/Widget.h
> +        void setSize(float x, float y);
I think having two overloads for the same thing differ by parameter and one virtual and one now will only cause problems. I would completely remove overloads that take separate floats like that and only keep the most abstracted parameters.

As a second point, I don't see how `setSize` being virtual could be used (same for `setPosition`, they are so basic that I don't see usages for overriding it, only issues)

2020-10-23 15:12 UTC, Sopel97 commented on src/core/widgets/Widget.h
> +        void setOrigin(sf::Vector2f origin);
how does origin differ from position? I don't understand its purpose

2020-10-23 15:12 UTC, Sopel97 commented on src/core/widgets/Widget.h
> +        virtual void setParent(Container* parent);
I don't see why this should be virtual. It's widget's job to track the parent.

2020-10-23 15:12 UTC, Sopel97 commented on src/core/widgets/Widget.h
> +        bool isContainer() const;
This is a weird method to have in a polymorphic type. I'm also not sure what it's purpose could be.

2020-10-23 15:12 UTC, Sopel97 commented on src/core/widgets/Widget.h
> +        sf::Vector2f m_position;
It's always a good question to rise here whether coordinates within a window should be integers or floats. I would think integers make more sense as windows are 2 dimensional and the coordinates have pixels as units.

2020-10-23 15:12 UTC, Sopel97 commented on src/core/widgets/Widget.h
> +        bool m_containerWidget = false;
again, I don't understand the purpose of this

2020-10-24 06:25 UTC, Kubaaa96 commented on src/core/Engine.cpp
> +        , containerPtr(std::make_unique<ire::core::widgets::Container>())
At this stage of development this feature i used it for testing purposes. Most of this things are temporary and coming from first refactoring iteration.

2020-10-24 06:26 UTC, Kubaaa96 commented on src/core/widgets/Button.cpp
> +		m_type = "Button";
I will add something like this. Thanks

2020-10-24 06:26 UTC, Kubaaa96 commented on src/core/widgets/Button.h
> +        std::unique_ptr<Button> create(const std::string& text = "");
it should be. I will change it

2020-10-24 07:41 UTC, Kubaaa96 commented on src/core/widgets/Widget.h
> +        sf::Vector2f m_position;
I will create Different type for Storing position as well as size of widgets. Vector2f is temporary

2020-10-24 07:46 UTC, Kubaaa96 commented on src/core/widgets/Widget.h
> +        void setOrigin(sf::Vector2f origin);
I created Origin to serve the same purpose as in SFML. To be center point of three transformation: Position, rotation and scaling.  We will see later how it will work out. If origin won't be useful or there won't be rotation or scaling i will delete that

2020-10-24 07:47 UTC, Kubaaa96 commented on src/core/widgets/Container.h
> +        std::unique_ptr<Widget> clone() const override
Containers need to clone all widgets they holding not only itself.

2020-10-25 14:14 UTC, Sopel97 commented on src/core/widgets/Button.cpp
>  	std::unique_ptr<Widget> Button::clone() const
is `Widget` not a pure abstract base? I would expect `virtual std::unique_ptr<Widget> Widget::clone() const = 0`

2020-10-25 14:14 UTC, Sopel97 commented on src/core/widgets/Button.h
> +        WidgetType getType() const override
It would be nice if there was also a way to get the type statically, without an instance. Though it can't have the same name. I'm not sure how this could be solved well, last time I proposed having the `static WidgetType type` be public and I don't have a better suggestion now, really.

2020-10-25 14:14 UTC, Sopel97 commented on src/core/widgets/ClickableWidget.cpp
> +	WidgetType ClickableWidget::m_type = WidgetType::create<ClickableWidget>("ClickableWidget");
like `Widget`, I would expect `ClickableWidget` to be an abstract base class, so neither `Widget` nor `ClickableWidget` would need to have a type.

2020-10-25 14:14 UTC, Sopel97 commented on src/core/widgets/Container.cpp
> +			m_widgets.erase(std::find_if(m_widgets.begin(), m_widgets.end(),
this is undefined behaviour if the element doesn't exist. This should be done by
```
auto it = std::find_if(m_widgets.begin(), m_widgets.end(), [&widgetName](auto& w) { return w->getWidgetName() == widgetName; });
if (it == m_widgets.end())
    return false;

m_widgets.erase(it);
return true;

2020-10-25 14:14 UTC, Sopel97 commented on src/core/widgets/Container.cpp
>  	bool Container::compareWithWidgetNameAt(std::size_t index, const std::string& name)
a non-const overload for this doesn't look needed. the non-const one doesn't modify state anyway

2020-10-25 14:14 UTC, Sopel97 commented on src/core/widgets/Container.h
> +#include <iostream>
why is `iostream` needed here? Looks like `string` is needed.

2020-10-25 14:14 UTC, Sopel97 commented on src/core/widgets/WidgetType.h
> +	uint64_t index;
std::uint64_t, as uint64_t is not required to be defined after `#include <cstdint>`

2020-10-25 14:14 UTC, Sopel97 commented on src/core/widgets/WidgetType.h
> +	uint64_t index;
I'd expect the instances of such a struct to be immutable, so `index` and `name` should be private state

2020-10-25 21:34 UTC, Sopel97 requested changes

2020-10-25 21:34 UTC, Sopel97 commented on src/core/widgets/Container.cpp
> +	const WidgetType Container::getType() const
returning by const value doesn't really change anything from returning by non-const value. It only prevents move construction.

2020-10-25 21:34 UTC, Sopel97 commented on src/core/widgets/WidgetType.h
> +	WidgetType(uint64_t index, std::string_view name) : m_index(index), m_name(name) {};
I think the constructor should be private.

2020-10-26 12:45 UTC, Sopel97 commented on src/core/widgets/Group.cpp
> +	}
I would consider having two positions in the widget.
1. relative to parent (`position`)
2. relative to the render area (`clientPosition`, or `aboslutePosition`)
The way it's done currently it too intrusive for my liking as sometimes the position is relative to the parent and sometimes absolute.

Maybe `absolutePosition` (or `clientPosition`) should be only a virtual method that is called when drawing (so no need to keep it updated with events)

One could push it further and instead of `sf::RenderTarget` pass something that encapsulates the render target and also keeps track of the current parent widget so that the widget can just draw itself "locally".

2020-10-26 12:45 UTC, Sopel97 commented on src/core/widgets/Group.cpp
> +				getPosition().y + widget->getPosition().y);
This is asking for `sf::Vector::operator+`

2020-10-26 12:45 UTC, Sopel97 commented on src/core/widgets/Container.cpp
> +
is this padding or offset to get the absolute position of the child?

2020-10-26 12:45 UTC, Sopel97 commented on src/core/Engine.cpp
> +        group->init();
Inits are kinda defying RAII, but since there's no events I guess that's the only way for now

2020-10-27 08:43 UTC, Sopel97 requested changes

2020-10-27 08:43 UTC, Sopel97 commented on src/core/widgets/BoxLayout.cpp
> +            Group::add(std::move(widgetPtr), widgetName);
It's weird that adding to the end calls `Group::add` but otherwise the `Group` is diregarded and uses group's internals.

2020-10-27 08:43 UTC, Sopel97 commented on src/core/widgets/BoxLayout.cpp
> +        updateWidgets();
If updateWidgets is a part of the group it would be easier to maintain correctness if it was being called from `Group::add` and `Group::remove`

2020-10-27 08:43 UTC, Sopel97 commented on src/core/widgets/BoxLayout.h
> +        float m_BottomMargin{ 0 };
Consider a `struct Margins {}` that collects all of these. Or something more generic like `template <typename T> struct ValuePerSide { T left, right, top, bottom };`

2020-10-27 08:43 UTC, Sopel97 commented on src/core/widgets/Container.h
> +        virtual void add(const std::unique_ptr<Widget> widgetPtr, const std::string& widgetName);
Can you even move the `unique_ptr` if you add const here?

2020-10-27 08:43 UTC, Sopel97 commented on src/core/widgets/HorizontalLayout.h
> +        static WidgetType m_type;
this should be `static const`.

2020-10-27 12:46 UTC, Kubaaa96 commented on src/core/widgets/BoxLayout.cpp
> +            Group::add(std::move(widgetPtr), widgetName);
Maybe i will change that. We will see how it work out

2020-10-27 13:04 UTC, Sopel97 commented on src/core/widgets/Margins.h
> +            float m_BottomMargin{ 0 };
naming convention? Also I think the `Margin` suffix is not necessary.

2020-10-27 13:04 UTC, Sopel97 commented on src/core/widgets/Margins.h
> +            Margins(Margins&);
`const Margins&`

2020-10-27 13:04 UTC, Sopel97 commented on src/core/widgets/Margins.h
> +            Margins& operator=(Margins&&) noexcept;
constructors and assignment operators could just be defaulted `= default`

2020-10-27 13:04 UTC, Sopel97 commented on src/core/widgets/Margins.h
> +            const float getBottomMargin() const;
since there's no validation I would consider making the members public

2020-10-27 19:41 UTC, Sopel97 requested changes

2020-10-27 19:41 UTC, Sopel97 commented on src/core/widgets/BoxLayout.h
> +        float m_spaces{1};
maybe something like `m_paddingBetweenWidgets` would be a better name.

2020-10-27 19:41 UTC, Sopel97 commented on src/core/widgets/Margins.h
> +            float m_Bottom{ 0 };
why upper case first letter after `_`?

2020-10-27 19:41 UTC, Sopel97 commented on src/core/widgets/VerticalLayout.cpp
> +	WidgetType const VerticalLayout::m_type = WidgetType::create<VerticalLayout>("Vertical Layout");
I think it would be nicer if the stringified named matched the class name, i.e. no spaces.

2020-10-27 19:41 UTC, Sopel97 commented on src/core/widgets/VerticalLayout.cpp
> +		const auto height = (size.y / sizeOfVector) - ((m_margins.m_Top + m_margins.m_Bottom + (m_spaces * (sizeOfVector - 1))) / sizeOfVector);
that's a very long and nested line

2020-10-28 07:56 UTC, Sopel97 approved these changes
Looks good

2020-10-28 13:03 UTC, Sopel97 approved these changes

2020-10-28 15:59 UTC, Sopel97 approved these changes

2020-10-28 15:59 UTC, Sopel97 commented on src/core/widgets/BoxLayout.h
> +        void setSpaces(float spaces);
I see that you didn't rename this after all. Maybe at least `setSpacing`? `setSpaces` doesn't really sound right

2020-10-28 19:14 UTC, Sopel97 commented on src/core/widgets/Panel.cpp
> +	Panel::Panel(const sf::Vector2f& size, std::unique_ptr<BoxLayout> mainPanelLayout, std::string& layoutName)
missing const before std::string

2020-10-28 19:14 UTC, Sopel97 commented on src/core/widgets/Panel.cpp
> +	std::unique_ptr<Panel> Panel::create(const sf::Vector2f size, std::unique_ptr<BoxLayout> mainPanelLayout, std::string& layoutName)
missing const before std::string

2020-10-28 19:14 UTC, Sopel97 commented on src/core/widgets/Panel.h
> +        Panel(const sf::Vector2f& size, std::unique_ptr<BoxLayout> mainPanelLayout, std::string& layoutName);
missing const before std::string

2020-10-28 19:14 UTC, Sopel97 commented on src/core/widgets/Panel.h
> +            std::unique_ptr<BoxLayout> mainPanelLayout, std::string& layoutName);
missing const before std::string

2020-10-29 13:15 UTC, Sopel97 requested changes

2020-10-29 13:15 UTC, Sopel97 commented on src/core/widgets/Group.cpp
> +			widget->setPosition(position + widgetPosition);
If you call updateWidgets twice in a row this is gonna get hairy. The absolute position and position relative to the parent should really be separated.

2020-10-29 13:15 UTC, Sopel97 commented on tests/core/widgets/HorizontalLayoutTests.cpp
> +			REQUIRE(layout->get("Button4")->getPosition() == sf::Vector2f({ 351, 54 }));
This is about where problems may start. You're using floats for positions and here you're doing equality comparison. The comparisons should be with some epsilon. There's `Approx` is catch.

2020-10-29 15:55 UTC, merged