[WIP]Layout Stretch fpr Gui and cleaning Code
Kubaaa96/Idle-Roman-Empire pull request #19
Opened 2020-10-30 20:11 UTC by Kubaaa96

- Current layout stretch system is based on QT style Layout Stretch
- Added ```m_layoutStretch``` member variable to BoxLayout
- Updated ```updateWidgets``` member functions in both horizontal and vertical Layouts based on validation of Stretch. If there is not stretch setup calculation will be as earlier. 
- Stretch is stored inside ```std::vector<int>``` 
- Main idea of current Layout Stretch system is to pass values for each widget inside of layout like ```layout->setLayoutStretch(...)``` where numbers of parameters inside ```setLayoutStretch``` method need to be equal to numbers of widgets in this layout. If its not the setting of stretch will be invalid and won't be used. 
- Calculation is based on ```n-th value / sumOfAllValues * size.y``` will be shown based on example: If you have VerticalLayout of ```y``` size = 1000 px, have 3 widgets inside, and use ```verticalLayout->setLayoutStretch(1, 2, 1); ``` First Widget will get value 250 because 1/4 * 1000 = 250, second one 2/4 * 1000 = 500, and so on. 
- Spaces and margins are subtracted from size of each widgets to fit them inside layout and if they are nested inside another layout 

- Image below is example of whole Gui system. Main layout of panel is set to Horizontal with 5 elements (4 Regular widget and one Vertical Layout on index 2) and Spaces are set to 10px, margins to ```({10, 10, 10, 10})``` (Left, Right, Top, Bottom). and Layout Stretch is set to ```({3, 6, 12, 2, 1}) Inside mainLayout on index 2 is Vertical Layout with 4 elements. Spaces are set to 5px, and margins to ```({0, 0, 15, 15})
- ![Example](https://cdn.discordapp.com/attachments/402207235893231616/771819734227484692/unknown.png)

2020-10-30 22:11 UTC, Sopel97 requested changes

2020-10-30 22:11 UTC, Sopel97 commented on src/core/widgets/BoxLayout.cpp
> +    void BoxLayout::setLayoutStretch(std::initializer_list<int> list)
This will not play well with code that creates dynamic amounts of widgets or wants to have more complicated logic for weights. `std::initializer_list` is not really usable apart from intizliation with constants. I would consider using a `std::vector` instead. Also the parameter name could be more descriptive - `weights`, `relativeSizes`. Also it's weird to me that everything uses floats but not this.

2020-10-30 22:11 UTC, Sopel97 commented on src/core/widgets/BoxLayout.cpp
> +            std::cout << "Size of list and widget vector is different. Need to be the same\n";
Please don't print on `std::cout` on errors. Library code should not be hijacking `std::cout` for diagnostics. Also there's no way for the caller to catch that. Throw an exception.

2020-10-30 22:11 UTC, Sopel97 commented on src/core/widgets/BoxLayout.cpp
>          updateWidgets();
dead code

2020-10-30 22:11 UTC, Sopel97 commented on src/core/widgets/BoxLayout.cpp
> +    const std::vector<int> BoxLayout::getLayoutStretch() const
returning by const value prevents move assignment. Perhaps this was supposed to be `const&`?

2020-10-30 22:11 UTC, Sopel97 commented on src/core/widgets/BoxLayout.cpp
> +            if (!std::equal(m_layoutStretch.begin() + 1, m_layoutStretch.end(), m_layoutStretch.begin()))
is `{1, 1}` really invalid?

2020-10-30 22:11 UTC, Sopel97 commented on src/core/widgets/ClickableWidget.h
> +        virtual void updateCurrentWidget() = 0;
What's "current" about it?

2020-10-30 22:11 UTC, Sopel97 commented on src/core/widgets/HorizontalLayout.cpp
> +
This logic is quite complicated, could you split it for "valid" and "invalid" cases more clearly?

2020-10-30 22:11 UTC, Sopel97 commented on src/core/widgets/VerticalLayout.cpp
> +
This almost the same as for the horizontal layout but with the other axis. Could they be merged into one with some member pointers?

2020-10-30 22:11 UTC, Sopel97 commented on src/core/widgets/Widget.cpp
> +	const sf::Vector2f Widget::getPosition() const
returning by const value is strictly worse than returning by non-const value

2020-10-30 22:11 UTC, Sopel97 commented on src/core/widgets/Widget.cpp
> +	const sf::Vector2f Widget::getLocalPosition() const
returning by const value is strictly worse than returning by non-const value

2020-10-30 22:11 UTC, Sopel97 commented on src/core/widgets/Widget.cpp
> +		std::cout << "Current Widget is not in any Layout so dont have Local Position \n";
don't print, throw

2020-10-30 22:11 UTC, Sopel97 commented on src/core/widgets/Widget.cpp
> +		std::cout << "Current Widget is not in any Layout so dont have Local Position \n";
if it doesn't have a parent then the local position is equal to position, but it DOES have a local position, no?

2020-10-30 22:11 UTC, Sopel97 commented on src/core/widgets/Widget.h
> +        virtual void setPosition(const sf::Vector2f& position, bool updateWidget = true);
So now there are two overloads for setPosition. One that is virtual and takes a vector and bool, one that is non-virtual and takes two floats. This is a serious code smell.

2020-10-30 22:11 UTC, Sopel97 commented on src/core/widgets/Widget.h
> +        virtual void setPosition(const sf::Vector2f& position, bool updateWidget = true);
now that there is `setLocalPosition` what purpose does `setPosition` serve? If it's [`setPosition`] only used internally by widgets for keeping the rendering position it should be kept protected without a public setter

2020-10-31 12:24 UTC, Kubaaa96 commented on src/core/widgets/HorizontalLayout.cpp
> +
Its a little bit complicated, but i will leave it for now. There can be changes in near future with this. Then i will try to split them

2020-10-31 13:35 UTC, Sopel97 requested changes

2020-10-31 13:35 UTC, Sopel97 commented on src/core/widgets/BoxLayout.cpp
> +            throw ("Size of list and widget vector is different. Need to be the same");
throwing a `const char[]` is a recipe for disaster, this should throw either a `std::runtime_error` or a class derived from it.

2020-10-31 13:35 UTC, Sopel97 commented on src/core/widgets/BoxLayout.cpp
> +            && !std::all_of(m_layoutStretch.begin() + 1, m_layoutStretch.end(), std::bind(std::equal_to<float>(),
I would prefer lambdas over `std::bind`. Moreover I still don't see why such layout stretches should be forbidden or handled differently?

2020-10-31 13:35 UTC, Sopel97 commented on src/core/widgets/HorizontalLayout.cpp
> +
Maybe get rid of `isValid...` altogether as it seems normal execution is a superset of the execution for the "invalid" case.

2020-10-31 13:40 UTC, Kubaaa96 commented on src/core/widgets/BoxLayout.cpp
> +            && !std::all_of(m_layoutStretch.begin() + 1, m_layoutStretch.end(), std::bind(std::equal_to<float>(),
Because {1,1} and all that have same numbers can be calculated using old method that is calculated before entering For loop in updateWidgets method. 

For different numbers you need to calculate before setting position and size of every widget in for loop. While they are the same size you don't

2020-10-31 21:04 UTC, Sopel97 requested changes

2020-10-31 21:04 UTC, Sopel97 commented on tests/core/Testsutils.h
> +bool areAlmostEqual(T sfvector, T sfvector2)
Shouldn't really be a template if it's not very generic. I would prefer an overload for `sf::Vector2f`.

2020-10-31 21:04 UTC, Sopel97 commented on tests/core/widgets/ButtonTests.cpp
> +#include "../Testsutils.h"
hmm, I think the cmakelists in tests should add tests directory to include directories so that this can be a forward relative path.

Also, Testsutils.h -> TestUtils.h

2020-10-31 21:04 UTC, Sopel97 commented on tests/core/widgets/ButtonTests.cpp
> +		REQUIRE(areAlmostEqual<sf::Vector2f>(button->getPosition(), sf::Vector2f({ 40, 50 })));
redundant `<sf::Vector2f>`

2020-11-01 17:50 UTC, Sopel97 approved these changes

2020-11-01 17:50 UTC, merged