[WIP] Basic states
Kubaaa96/Idle-Roman-Empire pull request #29
Opened 2020-11-15 15:04 UTC by Kubaaa96

Basic idea is to Change state when new is added to Stack stored in StateMachine.
- Added StateMachine to manage States and deciding what to do with them.
- Changed Root widget to Group from Panel in SystemWindow 
- Every State need have Group to set Root by ```m_window.setRootGroup(*group);```
- Temporary DrawGUI function returning Root Group in State
- Removed m_currentState from System Window
- States are most of the time created inside another states by using ``` StateMachine::build<state>(machine, window, replace);```

2020-11-15 20:48 UTC, Sopel97 requested changes

2020-11-15 20:48 UTC, Sopel97 commented on src/client/states/GameState.h
> +        core::gui::Group* drawGUI() override;
bad name, it doesn't draw it.

2020-11-15 20:48 UTC, Sopel97 commented on src/core/states/State.h
> +        State(StateMachine& machine, gui::SystemWindow& window, bool replace = true);
IMO replace=true is a bad default. I would leave it without a default value

2020-11-15 20:48 UTC, Sopel97 commented on src/core/states/StateMachine.h
> +        bool m_resume;
what's the meaning of this? I can't see how the name relates to the functionality, and frankly I don't see the functionality at all too.

2020-11-15 20:48 UTC, Sopel97 commented on src/core/states/StateMachine.h
> +
What's the purpose of this wrapper over make_unique? the name suggests it builds a state machine, but it just creates a state?

2020-11-15 20:48 UTC, Sopel97 commented on src/core/states/State.h
> +        StateMachine& m_machine;
m_machine is a very non-descriptive name for this. There can be many types of 'machines'

2020-11-16 19:08 UTC, Kubaaa96 commented
Example of current Working version
![Example](https://i.imgur.com/JIQpVlA.gif)

2020-11-16 19:08 UTC, Kubaaa96 commented on src/core/states/StateMachine.h
> +
I removed it for now

2020-11-17 19:57 UTC, Sopel97 approved these changes
Looks good to me now.

2020-11-18 08:35 UTC, merged