Edit box setup
Kubaaa96/Idle-Roman-Empire pull request #40
Opened 2020-12-03 15:48 UTC by Kubaaa96

![Example](https://i.imgur.com/ZFjA2xw.gif)
- Adding Text
- Setting Ghost Text
- Setting Max characters 
- Backspace and Delete functionaity
- Changing caret position by mouse, arrows, CTRL + arrows
- Selecting using mouse, SHIFT + arrows, CTRL + SHIFT + arrows
- CTRL + A
- CTRL + C
- CTRL + V
- CTRL + X

All tips how to improve this Shortcuts Ifs are welcome, as well as suggestion about where setup active item to allow inserting text while mouse is not inside of EditBox

2020-12-03 17:59 UTC, Sopel97 commented on src/core/gui/SystemWindow.cpp
> +        }
Ok, might be worth documenting this. I would expect all unicode code points to be handled, especially because sf::String should handle it well, but I guess this is a reasonable assumption, at least for now to keep it simple.

2020-12-03 17:59 UTC, Sopel97 commented on src/core/gui/SystemWindow.cpp
> +        forwardEvent(translatedEv);
what happens if the character is not in range?

2020-12-03 17:59 UTC, Sopel97 commented on src/core/gui/SystemWindow.h
> +            m_window.setFramerateLimit(60);
1. I cri with my 144hz.
2. Is this required? I'd prefer not setting it all, just so that we know our code is framerate independent.

2020-12-03 17:59 UTC, Sopel97 commented on src/core/gui/widgets/EditBox.cpp
>  	WidgetType const EditBox::m_type = WidgetType::create<EditBox>("EditBox");
tabs as indentation don't follow convention

2020-12-03 17:59 UTC, Sopel97 commented on src/core/gui/widgets/EditBox.cpp
> +			case 0:
I'd use std::optional

2020-12-03 17:59 UTC, Sopel97 commented on src/core/gui/widgets/EditBox.cpp
> +				break;
isn't `string.length() > m_maxChars` backwards? This will throw on strings that are shorter than m_maxChars

2020-12-03 17:59 UTC, Sopel97 commented on src/core/gui/widgets/EditBox.cpp
> +			// TODO Cut String if it is longer than m_maxChar and give info to client
This should be fairly easy to implement with substr, no? Also I don't think this function should ever throw like above as I'd not consider it to be an exceptional case; just return the number of charactes kept?

2020-12-03 17:59 UTC, Sopel97 commented on src/core/gui/widgets/EditBox.cpp
> +			|| ev.character == 22 || ev.character == 1)
Ok, we need some names for these magic constants, even locally.

2020-12-03 17:59 UTC, Sopel97 commented on src/core/gui/widgets/EditBox.cpp
> +			|| ev.character == 22 || ev.character == 1)
Overall this should be all ASCII characters < 32, as they are not printable.

2020-12-03 17:59 UTC, Sopel97 commented on src/core/gui/widgets/EditBox.cpp
> +		std::wstring_convert<std::codecvt_utf8<char32_t>, char32_t> conv;
I'll trust you on that, never touched this stuff

2020-12-03 17:59 UTC, Sopel97 commented on src/core/gui/widgets/EditBox.cpp
> +		switch (ev.key)
split these cases into functions

Personally I'd do one function for 			
case sf::Keyboard::Left: if (ev.control) { ... }
one for 
case sf::Keyboard::Left: if (ev.shift) { ... }
and so on, at this granularity

2020-12-03 17:59 UTC, Sopel97 commented on src/core/gui/widgets/EditBox.cpp
> +			deleteOneLetterBeforeCaret();
just like this :ok_hand:

2020-12-03 17:59 UTC, Sopel97 commented on src/core/gui/widgets/EditBox.cpp
> +			updateCaretPosition();
could be a separate function

2020-12-03 17:59 UTC, Sopel97 commented on src/core/gui/widgets/EditBox.cpp
> +	}
couldn't these call one function for `deleteCharacterAt`?
Also I'd change `letter` to `character` to be consistent with the rest

2020-12-03 17:59 UTC, Sopel97 commented on src/core/gui/widgets/EditBox.cpp
> +	void EditBox::updateIndexesOfWordStarting()
`updateWordIndices`?

2020-12-03 17:59 UTC, Sopel97 commented on src/core/gui/widgets/EditBox.cpp
> +		m_indexesOfWordStarting = tempIndexes;
Overall, as I understand this, it's for supporting word navigation, right? In this case I'm not sure it needs any persistent state, can't we just compute the next/prev word boundary during the event?

2020-12-03 17:59 UTC, Sopel97 commented on src/core/gui/widgets/EditBox.cpp
> +	std::size_t EditBox::findIndexOfLetterUnderMouse(float clickedXPosition)
`findPointedCharacterIndex`, `findIndexOfPointedCharacter`

2020-12-04 09:36 UTC, Kubaaa96 commented on src/core/gui/widgets/EditBox.cpp
> +		std::wstring_convert<std::codecvt_utf8<char32_t>, char32_t> conv;
There is a problem with that. ```std::wstring_convert``` is [deprecated](https://github.com/Kubaaa96/IdleRomanEmpire/runs/1493612483?check_suite_focus=true#step:11:26) i didn't try this other methods from warning. I believe it can be improved later

2020-12-04 13:28 UTC, Sopel97 requested changes

2020-12-04 13:28 UTC, Sopel97 commented on src/core/gui/SystemWindow.cpp
> +        forwardEvent(translatedEv);
what about this?

2020-12-04 13:28 UTC, Sopel97 commented on src/core/gui/widgets/EditBox.cpp
> +		switch (ev.key)
this is still one big blob

2020-12-04 13:28 UTC, Sopel97 commented on src/core/gui/widgets/EditBox.h
> +    enum class Alignment
I'd rename this to `HorizontalAlignment` and move it to a separate file, just so we have one definition for aligning anything

2020-12-05 11:37 UTC, Kubaaa96 commented on src/core/gui/widgets/EditBox.cpp
> +		m_indexesOfWordStarting = tempIndexes;
I try to experiment with that in next commit. This is just working first version

2020-12-05 11:40 UTC, Kubaaa96 commented on src/core/gui/widgets/EditBox.cpp
> +		switch (ev.key)
I does a little bit of refactoring. But after adding home/end its still contains 200 lines of code. The only case to lower lines of code is to separate whole shortcuts to functions, but names of them will be long in order to show what they doing. I believe we does not consider any ```ctrlShiftLeft()``` type of function naming. Right ?

2020-12-05 11:56 UTC, Kubaaa96 commented
TODO
- [ ] Fix inserting to string using CTRL + V while max char is set
- [ ] Add erasing selected substring using Backspace/Delete

2020-12-05 14:03 UTC, Sopel97 approved these changes
Ok. I guess we can address the alignment enum and the large onEvent function in further PR. This looks fine otherwise.

2020-12-05 18:45 UTC, merged