[WIP] Progress bar setup
Kubaaa96/Idle-Roman-Empire pull request #41
Opened 2020-12-21 11:53 UTC by Kubaaa96

- Progress bar with few texts that are possible to draw on top of Bar: Percent value, maximum value positioned on the left side, minimum value positioned on the right side, numerical value and text that is passed by create static function. All texts have possibility to show/hide it, set Character Size, set Fill Color and vertical alignment. 
- Vertical alignment was added to allow three texts to be displayed in the middle part. 
- For now there are 4 fill direction to choose from, but fully functional with position of all texts, are Left to Right. 
- There was an attempt to setup some value changed event but unsuccessful. 
- I'm open to suggestions how to make this texts properties, repeating functions more eye friendly. Because for now we setting more texts properties by calling specified for this text function. like for setting Character size of Value texts we call ``` setValueTextCharacterSize``` and for percent visibility ``` setPercentVisible```. There is probably much better way to do this that i haven't think about at this moment.
- Tests are partly done because most of the time i was trying to setup events

2020-12-21 13:50 UTC, Sopel97 requested changes

2020-12-21 13:50 UTC, Sopel97 commented on src/core/gui/CollectionOfEvents.h
> +#ifndef IRE_COLECTIONOFEVENTS
I don't like the name of this file. I'd just put it in the Events.h

2020-12-21 13:50 UTC, Sopel97 commented on src/core/gui/CollectionOfEvents.h
> +    struct KeyPressedEvent : TranslatedEvent
this event sounds very basic for a translated event, isn't this pretty much what the sfml gives us from the OS?

2020-12-21 13:50 UTC, Sopel97 commented on src/core/gui/Events.h
> +    struct ProgressBarValueChanged : RawEvent
that's definitely a `TranslatedEvent`

http://web.mit.edu/6.813/www/sp16/classes/09-input/

2020-12-21 13:50 UTC, Sopel97 commented on src/core/gui/Events.h
> +        float value;
Using a float value for the progress is an unusual choice. Generally what I've seen is that the progress bar keeps two values: current progress, and max progress, both of which are integers (uint64_t for example). This has 2 advantages:
1. no floating point math which is inaccurate
2. the user doesn't have to calculate the percentage himself

2020-12-21 13:50 UTC, Sopel97 commented on src/core/gui/RawEventHandler.h
> +        virtual void onEvent(EventRoot& sender, ProgressBarValueChanged& ev);
this should definitely not be there. It's not a raw event and should not be propagated through the widget tree.

2020-12-21 13:50 UTC, Sopel97 commented on src/core/gui/widgets/ProgressBar.cpp
> +	void ProgressBar::setMinimumTextVerticalAlighnment(VerticalTextAlignment minimumTextVerticalAlignment)
`Alighnment` typo

2020-12-21 13:50 UTC, Sopel97 commented on src/core/gui/widgets/ProgressBar.cpp
> +		if (m_value != value && m_value - m_minimum <= m_maximum - m_minimum)
hmm, so the value being set is relative to m_minimum? I'd not expect that. I would expect the value being in the same space as m_minimum and m_maximum

2020-12-21 13:50 UTC, Sopel97 commented on src/core/gui/widgets/ProgressBar.cpp
> +	void ProgressBar::onEvent(EventRoot& sender, ProgressBarValueChanged& ev)
umm, progress bar should emit this event, not handle it

2020-12-21 13:50 UTC, Sopel97 commented on src/core/gui/widgets/ProgressBar.cpp
> +			m_value = value;
doesn't emit the event?

2020-12-21 13:50 UTC, Sopel97 commented on src/core/gui/widgets/ProgressBar.cpp
> +			break;
?

2020-12-21 13:50 UTC, Sopel97 commented on src/core/gui/widgets/ProgressBar.h
> +        unsigned int m_minimum{ 0 };
minimum/maximum as ints and value as float? So I guess the progress is in percentages, more weirdly it is between 0 and 100 and not between 0 and 1. See the comment for the event struct.

2020-12-21 13:52 UTC, Sopel97 commented on src/core/gui/widgets/ProgressBar.cpp
> +		emitEvent<ValueChanged>(valueChangedEv);
this code is unreachable as far as I can see?

2020-12-22 20:18 UTC, Sopel97 commented on src/core/gui/widgets/ProgressBar.cpp
> +		emitEvent<ProgressBarValueChanged>(valueChangedEv);
I don't get this, why is it reconstructing the same event that it got as a parameter and reemits it?

2020-12-22 20:18 UTC, Sopel97 commented on src/core/gui/widgets/ProgressBar.cpp
>  	const float ProgressBar::calculatePercent() const
this function shouldn't throw. the value being in range should be an invariant kept by the setters.

2020-12-22 20:18 UTC, Sopel97 commented on src/core/gui/widgets/ProgressBar.h
> +        uint64_t m_value{ 50 };
this value is relative to the minimum. I'd say it's unintuitive and makes the concept of having a minimum pointless.

2020-12-25 14:02 UTC, Kubaaa96 commented
![Example](https://i.imgur.com/PA98yZI.gif)

2020-12-25 14:06 UTC, Kubaaa96 commented on src/core/gui/widgets/ProgressBar.h
> +        uint64_t m_value{ 50 };
I will change it later. Definitely before first serious usage.

2020-12-25 20:23 UTC, Sopel97 approved these changes

2020-12-26 03:19 UTC, merged