Text setup
Kubaaa96/Idle-Roman-Empire pull request #44
Opened 2020-12-27 19:44 UTC by Kubaaa96

This is basic encapsulation of Text in terms of drawing in SFML window. For now it's only expanding functionality of setting Vertical and Horizontal alignment in widget as well as adding possibility of allow or not changing alignment by changing bool value of public member variables m_isHAlign/m_isVAlign, showing/hiding using setVisibility/getVisibility, setting font. In future there will be needed great rework of this struct.

2020-12-27 21:34 UTC, Sopel97 requested changes

2020-12-27 21:34 UTC, Sopel97 commented on src/core/gui/Text.h
> +        bool m_isVAlign = true;
why have these? Text is always aligned *in some way*

2020-12-27 21:34 UTC, Sopel97 commented on src/core/gui/widgets/Button.cpp
> +		m_text.updateTextPosition(xPosition, yPosition, m_position, m_size);
`setTextPosition`? or simply `setPosition` since it's known that it's a text

2020-12-27 21:34 UTC, Sopel97 commented on src/core/gui/Text.cpp
> +	void Text::updateTextPosition(float xPosition, float yPosition, sf::Vector2f currentPosition, sf::Vector2f currentSize)
what's `currentPosition` and `currentSize`? Why are `xPosition` and `yPositions` parameters?

2020-12-27 21:34 UTC, Sopel97 commented on src/core/gui/widgets/Button.cpp
> +		m_text.updateTextPosition(xPosition, yPosition, m_position, m_size);
the first two parameters need to be definitely removed as it's just a convoluted way to pass text's own state into itself.

2020-12-27 21:34 UTC, Sopel97 commented on src/core/gui/Text.h
> +        void setVisibility(bool isVisible);
`setVisible`

2020-12-27 21:34 UTC, Sopel97 commented on src/core/gui/Text.h
> +        const bool getVisibility() const;
`isVisible`

2020-12-27 21:34 UTC, Sopel97 commented on src/core/gui/Text.h
> +        void setHAlign(HorizontalAlignment horizontalAlignment);
I'd spell horizontal and vertical fully, but if you think this is better it's fine

2020-12-28 07:12 UTC, Kubaaa96 commented on src/core/gui/Text.cpp
> +	void Text::updateTextPosition(float xPosition, float yPosition, sf::Vector2f currentPosition, sf::Vector2f currentSize)
i change ```currentPosition``` to ```positionOfWidget```, and ```currentSize``` to ```sizeOfWidget```. Text is setup based on widget position/size. I do not expect setting position without being in Widget.

2020-12-28 14:48 UTC, Sopel97 approved these changes

2020-12-28 15:13 UTC, merged