Buildings/Placement system
Kubaaa96/Idle-Roman-Empire pull request #51
Opened 2021-01-11 19:09 UTC by Kubaaa96

Basic placement concept system allowing to choose place for desired building, then using mouse click place it as well as detecting if planned building is over some already placed/ordered. Colors for each overlay in ordered/placed state is temporary and in future we will be using sprites. Entrance is represented by different color for now. To decide is still if we should allow many entrances to building.
![Example](https://i.imgur.com/cD56HtQ.gif)

2021-01-11 21:06 UTC, Sopel97 requested changes

2021-01-11 21:06 UTC, Sopel97 commented on src/client/Game/Objects/Building.cpp
> +        return m_orderedOverlays;
I presume that when the relevant mechanics are done this will be replaced with sprites in some other (building) layer? I see the overlays as something that we should only use for "indicators"; when the building is placed (ordered) it becomes an entity that's part of the map and should be rendered along with other buildings. Do you share my thoughs on this?

2021-01-11 21:06 UTC, Sopel97 commented on src/client/Game/Objects/Building.h
> +            Demaged
Demaged -> Damaged

2021-01-11 21:06 UTC, Sopel97 commented on src/client/Game/Objects/Object.h
> +        std::uint64_t m_Id;
m_Id -> m_id?

2021-01-11 21:06 UTC, Sopel97 commented on src/client/Game/Objects/Object.h
> +        std::uint64_t m_Id;
We should perhaps consider a typedef for IDs? `using ObjectId = std::uint64_t`? Would be easier to make the ids strong types in the future if desirable.

2021-01-11 21:06 UTC, Sopel97 commented on src/client/Game/Objects/Object.h
> +        sf::Vector2i m_currentPosition;
Maybe just `m_position`? There's no other position.

2021-01-11 21:06 UTC, Sopel97 commented on src/client/Game/Objects/ObjectMenager.h
> +    struct ObjectMenager
Menager -> Manager

2021-01-11 21:06 UTC, Sopel97 commented on src/client/Game/Objects/ObjectMenager.h
> +        std::vector<std::unique_ptr<Building>> m_collectionOfBuildings;
just m_buildings?

2021-01-11 21:06 UTC, Sopel97 commented on src/client/Game/Objects/ObjectMenager.h
> +        const bool isCollectionOfBuildingsEmpty() const;
isEmpty? or if we want to disambiguate with future different types then numBuildings?

2021-01-11 21:06 UTC, Sopel97 commented on src/client/gui/widgets/WorldView.cpp
> +    WorldView::WorldView(ire::core::world::World& world, objects::ObjectMenager& objectMenager) :
I think the `ObjectManager` should be encapsulated by the surface. For two reasons. 1. Because it makes sense. 2. Because different surfaces will have different objects (and a world can cosist of multiple surfaces)

2021-01-11 21:06 UTC, Sopel97 commented on src/client/gui/widgets/WorldView.h
> +        const std::optional<sf::Vector2f> getMousePos() const;
Not sure if this should be a public interface. The way position is tracked here is kinda hacky and I expect it to be replaced in the future.

2021-01-11 21:06 UTC, Sopel97 commented on src/client/gui/widgets/WorldView.h
> +        const std::optional<sf::Vector2f> getMousePos() const;
It's certainly not one of the responsibilities of this class to provide mouse position

2021-01-11 21:06 UTC, Sopel97 commented on src/client/states/GameState.h
> +        std::unique_ptr<objects::ObjectMenager> m_objectMenager;
Manager

2021-01-11 21:06 UTC, Sopel97 commented on src/client/gui/widgets/WorldView.cpp
> +    WorldView::WorldView(ire::core::world::World& world, objects::ObjectMenager& objectMenager) :
This also means that all the `Object` stuff should be part of `core`

2021-01-11 21:06 UTC, Sopel97 commented on src/core/gui/widgets/ClickableWidget.cpp
> +		//sender.setActiveWidget(*this);
hmm?

2021-01-11 21:06 UTC, Sopel97 commented on src/core/world/tiled_top_down/TiledTopDownSurface.h
> +        void pushBackTileOverlay(TileOverlay& overlay);
addTileOverlay? Take by `const&`.

2021-01-11 21:06 UTC, Sopel97 commented
Looking cool! Just minor stuff that needs to be addressed.

2021-01-12 03:34 UTC, Kubaaa96 commented on src/client/Game/Objects/Building.cpp
> +        return m_orderedOverlays;
Yes. Overlay will be used only in Planning state. Ordered is when building is placed so clicked on map during planning state

2021-01-12 03:53 UTC, Kubaaa96 commented on src/client/gui/widgets/WorldView.cpp
> +    WorldView::WorldView(ire::core::world::World& world, objects::ObjectMenager& objectMenager) :
I will do that in next PR probably. It will be similar basic stuff for NPCs i believe.

2021-01-12 03:55 UTC, Kubaaa96 commented on src/client/gui/widgets/WorldView.h
> +        const std::optional<sf::Vector2f> getMousePos() const;
I think we should leave that for now. You are right, but for now its used in ```                    auto pointedTilePos = mainSurface.mapClientToTilePosition(m_window.getRenderTarget(), *worldViewRef.getMousePos());
``` in GameState.cpp 73. If more sophisticated position tracker will be implemented it can be change as well.

2021-01-12 11:31 UTC, Sopel97 requested changes

2021-01-12 11:31 UTC, Sopel97 commented on src/client/Game/Objects/ObjectManager.h
> +        Building* m_currentSelectedBuilding = nullptr;
why is this public?

2021-01-12 11:31 UTC, Sopel97 commented on src/client/gui/widgets/WorldView.h
> +        const std::optional<sf::Vector2f> getMousePos() const;
Maybe WorldView should have a function `getPointedTile` and pass the mouse pos down to the surface?

2021-01-12 11:31 UTC, Sopel97 commented on src/client/gui/widgets/WorldView.h
> +        objects::ObjectManager* m_objectManager;
this is still not a part of the surface

2021-01-12 11:32 UTC, Sopel97 commented on src/client/gui/widgets/WorldView.cpp
> +    WorldView::WorldView(ire::core::world::World& world, objects::ObjectMenager& objectMenager) :
ok, just don't forget ;d

2021-01-12 14:56 UTC, Sopel97 approved these changes

2021-01-12 14:57 UTC, Sopel97 commented
I don't like that the surface contains the mouse pos as it couples it with the presentation layer, but that can be addressed in the future.

2021-01-12 15:15 UTC, merged